codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 75%
        threshold: 5%
        if_ci_failed: error

  ignore:
    - "tests/*"
    - "setup.py"
    - "*/test_*.py"
    - "examples/*"
    - "docs/*"
    - "scripts/*"
    - "web-app/*"
    - "backend/*"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

github_checks:
  annotations: true
