name: Validate CITATION.cff

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-cff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install cffconvert
        run: |
          python -m pip install --upgrade pip
          pip install cffconvert

      - name: Validate CITATION.cff
        run: |
          cffconvert -i CITATION.cff -o /dev/null
